# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_agendamento_varredura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ativorede",
            name="origem",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("snmp", "SNMP"),
                    ("ad", "Active Directory"),
                    ("agente", "Agente"),
                    ("importacao", "Importação"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
