# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_origem_agente"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativorede",
            name="arquitetura",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="ativorede",
            name="processador",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="ativorede",
            name="memoria_total_gb",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="ativorede",
            name="disco_total_gb",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="ativorede",
            name="office",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="ativorede",
            name="usuario_logado",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="ativorede",
            name="dominio",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
