# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_detalhes_hardware_software"),
    ]

    operations = [
        migrations.AddField(
            model_name="ativorede",
            name="softwares_instalados",
            field=models.TextField(blank=True),
        ),
    ]
