# Generated by Django 5.2.14 on 2026-06-09 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_softwares_instalados'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicencaSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('fabricante', models.CharField(blank=True, max_length=120)),
                ('chave', models.CharField(blank=True, max_length=180)),
                ('quantidade_total', models.PositiveIntegerField(default=1)),
                ('validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('a_vencer', 'A vencer'), ('vencida', 'Vencida'), ('suspensa', 'Suspensa')], default='ativa', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativos', models.ManyToManyField(blank=True, related_name='licencas', to='inventario.ativorede')),
            ],
            options={
                'verbose_name': 'licenca de software',
                'verbose_name_plural': 'licencas de software',
                'ordering': ['nome', 'fabricante'],
            },
        ),
        migrations.CreateModel(
            name='RelacionamentoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('depende_de', 'Depende de'), ('conectado_a', 'Conectado a'), ('hospeda', 'Hospeda'), ('usa_servico', 'Usa servico'), ('impacta', 'Impacta')], default='depende_de', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_destino', to='inventario.ativorede')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacoes_origem', to='inventario.ativorede')),
            ],
            options={
                'verbose_name': 'relacionamento de ativo',
                'verbose_name_plural': 'relacionamentos de ativos',
                'ordering': ['origem__nome', 'destino__nome'],
            },
        ),
    ]
