# Generated by Django 5.2.14 on 2026-06-10 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_licencasoftware_relacionamentoativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoLicencaSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='licencas/anexos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('licenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='inventario.licencasoftware')),
            ],
            options={
                'verbose_name': 'anexo de licenca',
                'verbose_name_plural': 'anexos de licencas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAlteracaoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=120)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_novo', models.TextField(blank=True)),
                ('origem', models.CharField(default='sistema', max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='inventario.ativorede')),
            ],
            options={
                'verbose_name': 'historico de alteracao do ativo',
                'verbose_name_plural': 'historicos de alteracoes dos ativos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
