# Generated by Django 5.2.14 on 2026-06-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_anexolicencasoftware_historicoalteracaoativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentovarredura',
            name='metodo',
            field=models.CharField(choices=[('auto', 'Automático'), ('ping', 'Ping / ICMP'), ('dns', 'DNS reverso'), ('tcp', 'TCP / portas'), ('snmp', 'SNMP'), ('ad', 'Active Directory'), ('winrm', 'WinRM / WMI'), ('csv', 'Importação CSV'), ('manual', 'Cadastro manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='metododescoberta',
            name='codigo',
            field=models.CharField(choices=[('auto', 'Automático'), ('ping', 'Ping / ICMP'), ('dns', 'DNS reverso'), ('tcp', 'TCP / portas'), ('snmp', 'SNMP'), ('ad', 'Active Directory'), ('winrm', 'WinRM / WMI'), ('csv', 'Importação CSV'), ('manual', 'Cadastro manual')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='varredurarede',
            name='metodo',
            field=models.CharField(choices=[('auto', 'Automático'), ('ping', 'Ping / ICMP'), ('dns', 'DNS reverso'), ('tcp', 'TCP / portas'), ('snmp', 'SNMP'), ('ad', 'Active Directory'), ('winrm', 'WinRM / WMI'), ('csv', 'Importação CSV'), ('manual', 'Cadastro manual')], default='auto', max_length=20),
        ),
    ]
