# Generated by Django 5.2.14 on 2026-06-23 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0016_artigos_base_conhecimento_ti'),
        ('inventario', '0009_alter_agendamentovarredura_metodo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ativorede',
            name='ciclo_vida',
            field=models.CharField(choices=[('estoque', 'Em estoque'), ('em_uso', 'Em uso'), ('manutencao', 'Em manutencao'), ('emprestado', 'Emprestado'), ('baixado', 'Baixado'), ('descartado', 'Descartado')], default='em_uso', max_length=20),
        ),
        migrations.AddField(
            model_name='ativorede',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativorede',
            name='data_baixa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativorede',
            name='garantia_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativorede',
            name='motivo_baixa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ativorede',
            name='patrimonio',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.CreateModel(
            name='MovimentacaoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_origem', models.CharField(blank=True, max_length=150)),
                ('local_destino', models.CharField(blank=True, max_length=150)),
                ('responsavel_origem', models.CharField(blank=True, max_length=150)),
                ('responsavel_destino', models.CharField(blank=True, max_length=150)),
                ('ciclo_anterior', models.CharField(choices=[('estoque', 'Em estoque'), ('em_uso', 'Em uso'), ('manutencao', 'Em manutencao'), ('emprestado', 'Emprestado'), ('baixado', 'Baixado'), ('descartado', 'Descartado')], max_length=20)),
                ('ciclo_novo', models.CharField(choices=[('estoque', 'Em estoque'), ('em_uso', 'Em uso'), ('manutencao', 'Em manutencao'), ('emprestado', 'Emprestado'), ('baixado', 'Baixado'), ('descartado', 'Descartado')], max_length=20)),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='inventario.ativorede')),
                ('movimentado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='chamados.setor')),
                ('setor_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='chamados.setor')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SondaRemota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('localidade', models.CharField(blank=True, max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('token_hash', models.CharField(editable=False, max_length=256)),
                ('token_prefixo', models.CharField(blank=True, editable=False, max_length=12)),
                ('ativa', models.BooleanField(default=True)),
                ('ultima_comunicacao_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_mensagem', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('faixas', models.ManyToManyField(blank=True, related_name='sondas', to='inventario.faixarede')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoSonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=20)),
                ('ativos_encontrados', models.PositiveIntegerField(default=0)),
                ('mensagem', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sonda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='inventario.sondaremota')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroColetaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('rejeitada', 'Rejeitada')], max_length=20)),
                ('mensagem', models.CharField(blank=True, max_length=500)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('versao_agente', models.CharField(blank=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_coleta', to='inventario.ativorede')),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'criado_em'], name='inventario__status_7c1976_idx')],
            },
        ),
    ]
