# Generated by Django 5.2.14 on 2026-06-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_ativorede_ciclo_vida_ativorede_data_aquisicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativorede',
            name='coleta_solicitada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
