# Generated by Django 5.2.14 on 2026-06-23 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0016_artigos_base_conhecimento_ti'),
        ('inventario', '0011_ativorede_coleta_solicitada_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoResponsabilidadeAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrega', 'Entrega'), ('devolucao', 'Devolucao'), ('emprestimo', 'Emprestimo')], max_length=20)),
                ('responsavel', models.CharField(max_length=180)),
                ('matricula', models.CharField(blank=True, max_length=80)),
                ('finalidade', models.TextField(blank=True)),
                ('texto_termo', models.TextField()),
                ('data_evento', models.DateField()),
                ('assinatura_nome', models.CharField(blank=True, max_length=180)),
                ('aceite_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termos_responsabilidade', to='inventario.ativorede')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chamados.setor')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
