# Generated by Django 5.2.14 on 2026-07-06 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_termoresponsabilidadeativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('link', 'Link externo'), ('iframe', 'Iframe embutido')], default='link', max_length=20)),
                ('url_template', models.CharField(help_text='Use variaveis como {{ ip }}, {{ hostname }}, {{ nome }}, {{ patrimonio }} ou campos externos.', max_length=600)),
                ('abrir_em_nova_aba', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'integracao externa',
                'verbose_name_plural': 'integracoes externas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcessoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_gerada', models.CharField(max_length=800)),
                ('modo', models.CharField(blank=True, max_length=20)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_integracoes', to='inventario.ativorede')),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='inventario.integracaoexterna')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acesso a integracao',
                'verbose_name_plural': 'acessos a integracoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CampoExternoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.SlugField(max_length=80)),
                ('valor', models.CharField(max_length=250)),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_externos', to='inventario.ativorede')),
            ],
            options={
                'verbose_name': 'campo externo do ativo',
                'verbose_name_plural': 'campos externos dos ativos',
                'ordering': ['chave'],
                'unique_together': {('ativo', 'chave')},
            },
        ),
    ]
