# Generated by Django 5.2.14 on 2026-06-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='logo_altura_max',
            field=models.PositiveIntegerField(default=38, verbose_name='altura máxima da logo (px)'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='logo_largura_max',
            field=models.PositiveIntegerField(default=46, verbose_name='largura máxima da logo (px)'),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='tema_visual',
            field=models.CharField(choices=[('personalizado', 'Personalizado'), ('clean', 'Clean'), ('blue', 'Blue'), ('dark', 'Dark'), ('red', 'Red'), ('green', 'Green'), ('corporate', 'Corporate')], default='blue', max_length=20),
        ),
    ]
