# Generated by Django 5.2.14 on 2026-06-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaoinstitucional_logo_altura_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoinstitucional',
            name='logo_altura_max',
        ),
        migrations.RemoveField(
            model_name='configuracaoinstitucional',
            name='logo_largura_max',
        ),
    ]
