# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_configuracaoinstitucional_logo_altura_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoinstitucional",
            name="portal_rotulo",
            field=models.CharField(default="Service desk", max_length=80),
        ),
        migrations.AddField(
            model_name="configuracaoinstitucional",
            name="portal_titulo",
            field=models.CharField(default="Abrir chamado de TI", max_length=120),
        ),
        migrations.AddField(
            model_name="configuracaoinstitucional",
            name="portal_subtitulo",
            field=models.TextField(
                blank=True,
                default="Registre sua solicitacao para a equipe tecnica acompanhar, priorizar e documentar o atendimento.",
            ),
        ),
        migrations.AddField(
            model_name="configuracaoinstitucional",
            name="portal_texto_apoio",
            field=models.TextField(
                blank=True,
                default="Informe o setor correto, descreva mensagens de erro, equipamento afetado e impacto no trabalho.",
            ),
        ),
    ]
