# Generated by Django 5.2.14 on 2026-06-09 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_portal_customizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criacao'), ('alteracao', 'Alteracao'), ('exclusao', 'Exclusao')], max_length=20)),
                ('app_label', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('objeto_id', models.CharField(blank=True, max_length=80)),
                ('objeto', models.CharField(blank=True, max_length=250)),
                ('caminho', models.CharField(blank=True, max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
