# Generated by Django 5.2.14 on 2026-06-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registroauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('intervalo_horas', models.PositiveIntegerField(default=24)),
                ('pasta_destino', models.CharField(blank=True, max_length=500)),
                ('manter_ultimos', models.PositiveIntegerField(default=15)),
                ('validar_automaticamente', models.BooleanField(default=True)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('proxima_execucao', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('invalido', 'Invalido')], max_length=20)),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('destino', models.CharField(blank=True, max_length=500)),
                ('mensagem', models.TextField(blank=True)),
                ('validado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
