# Generated by Django 5.2.14 on 2026-06-23 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configuracaobackup_registrobackup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLDAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('servidor', models.CharField(blank=True, max_length=255)),
                ('porta', models.PositiveIntegerField(default=389)),
                ('usar_ssl', models.BooleanField(default=False)),
                ('usuario_bind', models.CharField(blank=True, max_length=255)),
                ('senha_criptografada', models.TextField(blank=True, editable=False)),
                ('base_dn', models.CharField(blank=True, max_length=255)),
                ('filtro_usuarios', models.CharField(default='(objectClass=user)', max_length=255)),
                ('filtro_computadores', models.CharField(default='(objectClass=computer)', max_length=255)),
                ('atributo_login', models.CharField(default='sAMAccountName', max_length=80)),
                ('atributo_nome', models.CharField(default='givenName', max_length=80)),
                ('atributo_sobrenome', models.CharField(default='sn', max_length=80)),
                ('atributo_email', models.CharField(default='mail', max_length=80)),
                ('sincronizar_ativos', models.BooleanField(default=True)),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('mensagem', models.TextField()),
                ('nivel', models.CharField(choices=[('info', 'Informacao'), ('sucesso', 'Sucesso'), ('alerta', 'Alerta'), ('critico', 'Critico')], default='info', max_length=20)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('chave', models.CharField(blank=True, db_index=True, max_length=180)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('email_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'lida_em', 'criado_em'], name='core_notifi_usuario_3cb879_idx')],
            },
        ),
    ]
