# Generated by Django 5.2.14 on 2026-07-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracaoldap_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('criacao', 'Criacao'), ('alteracao', 'Alteracao'), ('exclusao', 'Exclusao'), ('login', 'Login'), ('logout', 'Logout'), ('exportacao', 'Exportacao'), ('api', 'API')], max_length=20),
        ),
    ]
