# Generated by Django 5.2.14 on 2026-07-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registroauditoria_ip_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='cor_menu_texto',
            field=models.CharField(default='#d7e5ff', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaoinstitucional',
            name='cor_texto',
            field=models.CharField(default='#172033', max_length=20),
        ),
    ]
