# Generated by Django 5.2.14 on 2026-07-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configuracaoinstitucional_cor_menu_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoinstitucional',
            name='cor_menu_texto',
            field=models.CharField(default='#1f2937', max_length=20),
        ),
    ]
