# Generated by Django 5.2.14 on 2026-06-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0010_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='impacto',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', max_length=20),
        ),
        migrations.AddField(
            model_name='chamado',
            name='primeira_resposta_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='primeira resposta'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipo',
            field=models.CharField(choices=[('incidente', 'Incidente'), ('requisicao', 'Requisição de serviço'), ('problema', 'Problema'), ('mudanca', 'Mudança')], default='incidente', max_length=20),
        ),
        migrations.AddField(
            model_name='chamado',
            name='urgencia',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='servicocatalogo',
            name='tipo_chamado',
            field=models.CharField(choices=[('incidente', 'Incidente'), ('requisicao', 'Requisição de serviço'), ('problema', 'Problema'), ('mudanca', 'Mudança')], default='requisicao', max_length=20),
        ),
    ]
