# Generated by Django 5.2.14 on 2026-06-09 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_chamado_impacto_chamado_primeira_resposta_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('membros', models.ManyToManyField(blank=True, related_name='equipes_atendimento', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipe de atendimento',
                'verbose_name_plural': 'equipes de atendimento',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='equipe_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='chamados.equipeatendimento'),
        ),
        migrations.CreateModel(
            name='RegraSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(blank=True, choices=[('incidente', 'Incidente'), ('requisicao', 'Requisição de serviço'), ('problema', 'Problema'), ('mudanca', 'Mudança')], max_length=20)),
                ('prioridade', models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('prazo_solucao_horas', models.PositiveIntegerField(default=48)),
                ('prazo_primeira_resposta_horas', models.PositiveIntegerField(default=4)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_sla', to='chamados.categoria')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_sla', to='chamados.equipeatendimento')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_sla', to='chamados.setor')),
            ],
            options={
                'verbose_name': 'regra de SLA',
                'verbose_name_plural': 'regras de SLA',
                'ordering': ['prazo_solucao_horas', 'nome'],
            },
        ),
    ]
