# Generated by Django 5.2.14 on 2026-06-09 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_equipeatendimento_chamado_equipe_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='aprovacao_necessaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamado',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aprovado em'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicocatalogo',
            name='aprovador_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_aprovador_padrao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicocatalogo',
            name='campos_personalizados',
            field=models.JSONField(blank=True, default=list, help_text='Lista JSON de campos. Exemplo: [{"nome":"cpf","rotulo":"CPF","tipo":"texto","obrigatorio":true}]'),
        ),
        migrations.AddField(
            model_name='servicocatalogo',
            name='equipe_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_padrao', to='chamados.equipeatendimento'),
        ),
        migrations.AddField(
            model_name='solicitacaoservico',
            name='dados_personalizados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em análise'), ('em_atendimento', 'Em atendimento'), ('aguardando_aprovacao', 'Aguardando aprovação'), ('aguardando_usuario', 'Aguardando usuário'), ('aguardando_fornecedor', 'Aguardando fornecedor'), ('resolvido', 'Resolvido'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='aberto', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicochamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em análise'), ('em_atendimento', 'Em atendimento'), ('aguardando_aprovacao', 'Aguardando aprovação'), ('aguardando_usuario', 'Aguardando usuário'), ('aguardando_fornecedor', 'Aguardando fornecedor'), ('resolvido', 'Resolvido'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], max_length=30),
        ),
    ]
