# Generated by Django 5.2.14 on 2026-06-10 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0014_artigos_agente_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mudanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_aprovacao', 'Aguardando aprovacao'), ('aprovada', 'Aprovada'), ('em_execucao', 'Em execucao'), ('validacao', 'Validacao'), ('concluida', 'Concluida'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=25)),
                ('risco', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=20)),
                ('impacto', models.TextField(blank=True)),
                ('plano_execucao', models.TextField()),
                ('plano_rollback', models.TextField()),
                ('janela_inicio', models.DateTimeField(blank=True, null=True)),
                ('janela_fim', models.DateTimeField(blank=True, null=True)),
                ('validacao_pos_mudanca', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas', to='chamados.chamado')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mudancas_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mudanca',
                'verbose_name_plural': 'mudancas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('investigacao', 'Em investigacao'), ('erro_conhecido', 'Erro conhecido'), ('workaround', 'Workaround publicado'), ('resolvido', 'Resolvido'), ('encerrado', 'Encerrado')], default='investigacao', max_length=20)),
                ('causa_raiz', models.TextField(blank=True)),
                ('workaround', models.TextField(blank=True)),
                ('solucao_definitiva', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('chamado_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_principais', to='chamados.chamado')),
                ('chamados_relacionados', models.ManyToManyField(blank=True, related_name='problemas', to='chamados.chamado')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problemas_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'problema',
                'verbose_name_plural': 'problemas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CampoServicoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.SlugField(max_length=80)),
                ('rotulo', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('texto', 'Texto curto'), ('texto_longo', 'Texto longo'), ('numero', 'Numero'), ('data', 'Data'), ('email', 'E-mail'), ('checkbox', 'Sim/Nao'), ('selecao', 'Lista de opcoes')], default='texto', max_length=20)),
                ('opcoes', models.TextField(blank=True, help_text='Uma opcao por linha. Usado apenas para campos do tipo lista de opcoes.')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='chamados.servicocatalogo')),
            ],
            options={
                'verbose_name': 'campo do servico',
                'verbose_name_plural': 'campos dos servicos',
                'ordering': ['ordem', 'rotulo'],
                'unique_together': {('servico', 'nome')},
            },
        ),
    ]
