# Generated by Django 5.2.14 on 2026-07-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramabpmn',
            name='exibir_portal',
            field=models.BooleanField(default=False, verbose_name='exibir no portal público'),
        ),
    ]
