# Generated by Django 5.2.14 on 2026-06-16 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInfra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('topologia', 'Topologia'), ('rede', 'Rede'), ('credencial', 'Credenciais e acessos'), ('servidor', 'Servidor'), ('sistema', 'Sistema'), ('procedimento', 'Procedimento'), ('outro', 'Outro')], default='topologia', max_length=30)),
                ('criticidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('localizacao', models.CharField(blank=True, max_length=180, verbose_name='localização/unidade')),
                ('resumo', models.TextField(blank=True)),
                ('conteudo', models.TextField(blank=True, verbose_name='documentação técnica')),
                ('conteudo_restrito', models.TextField(blank=True, help_text='Use para senhas, chaves, configurações sensíveis e observações de acesso.', verbose_name='informações restritas')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_infra_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_infra_criados', to=settings.AUTH_USER_MODEL)),
                ('usuarios_autorizados', models.ManyToManyField(blank=True, help_text='Superusuários sempre possuem acesso. Demais usuários precisam estar nesta lista.', related_name='documentos_infra_autorizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documentação de infraestrutura',
                'verbose_name_plural': 'documentações de infraestrutura',
                'ordering': ['tipo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='AnexoDocumentoInfra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentacao_infra/anexos/%Y/%m/')),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='documentacao.documentoinfra')),
            ],
            options={
                'verbose_name': 'anexo de documentação de infraestrutura',
                'verbose_name_plural': 'anexos de documentação de infraestrutura',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AcessoDocumentoInfra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('visualizacao', 'Visualização'), ('criacao', 'Criação'), ('edicao', 'Edição'), ('anexo', 'Anexo')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to='documentacao.documentoinfra')),
            ],
            options={
                'verbose_name': 'log de acesso à documentação',
                'verbose_name_plural': 'logs de acesso à documentação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
