from django.urls import path

from . import views


app_name = "chamados"

urlpatterns = [
    path("", views.PortalChamadoCreateView.as_view(), name="portal_abrir"),
    path("consultar/", views.PortalConsultaView.as_view(), name="portal_consultar"),
    path("consultar/<int:pk>/responder/", views.responder_chamado_portal, name="portal_responder"),
    path("consultar/<int:pk>/avaliar/", views.avaliar_chamado_portal, name="portal_avaliar"),
    path("consultar/<int:pk>/reabrir/", views.reabrir_chamado_portal, name="portal_reabrir"),
    path("conhecimento/", views.ArtigoConhecimentoPublicListView.as_view(), name="conhecimento"),
    path("conhecimento/<slug:slug>/", views.ArtigoConhecimentoPublicDetailView.as_view(), name="artigo_detalhe"),
    path("catalogo/", views.CatalogoServicoListView.as_view(), name="catalogo"),
    path("catalogo/<slug:slug>/", views.CatalogoServicoSolicitarView.as_view(), name="catalogo_solicitar"),
    path("gestao/busca/", views.BuscaGlobalView.as_view(), name="busca_global"),
    path("gestao/aprovacoes/", views.AprovacaoListView.as_view(), name="aprovacoes"),
    path("gestao/aprovacoes/<int:pk>/<slug:decisao>/", views.decidir_aprovacao, name="decidir_aprovacao"),
    path("gestao/", views.PainelView.as_view(), name="painel"),
    path("gestao/chamados/", views.ChamadoListView.as_view(), name="lista"),
    path("gestao/chamados/fila/<slug:fila>/", views.ChamadoListView.as_view(), name="fila"),
    path("gestao/chamados/novo/", views.ChamadoCreateView.as_view(), name="novo"),
    path("gestao/chamados/<int:pk>/", views.ChamadoDetailView.as_view(), name="detalhe"),
    path("gestao/chamados/<int:pk>/imprimir/", views.ChamadoPrintView.as_view(), name="imprimir"),
    path("gestao/chamados/<int:pk>/editar/", views.ChamadoUpdateView.as_view(), name="editar"),
    path("gestao/chamados/<int:pk>/encerrar/", views.encerrar_chamado, name="encerrar"),
    path("gestao/chamados/<int:pk>/atribuir-mim/", views.atribuir_chamado_mim, name="atribuir_mim"),
    path("gestao/chamados/<int:pk>/atribuir/", views.atribuir_chamado, name="atribuir"),
    path("gestao/chamados/<int:pk>/resolver-rapido/", views.resolver_chamado_rapido, name="resolver_rapido"),
    path("gestao/chamados/<int:pk>/tarefas/nova/", views.criar_tarefa_chamado, name="tarefa_nova"),
    path("gestao/chamados/<int:pk>/responder/", views.responder_chamado, name="responder"),
    path("gestao/chamados/<int:pk>/anexos/novo/", views.anexar_arquivo_chamado, name="anexo_novo"),
    path("gestao/setores/", views.SetorListView.as_view(), name="setores"),
    path("gestao/setores/novo/", views.SetorCreateView.as_view(), name="setor_novo"),
    path("gestao/setores/<int:pk>/editar/", views.SetorUpdateView.as_view(), name="setor_editar"),
    path("gestao/categorias/", views.CategoriaListView.as_view(), name="categorias"),
    path("gestao/categorias/novo/", views.CategoriaCreateView.as_view(), name="categoria_nova"),
    path("gestao/categorias/<int:pk>/editar/", views.CategoriaUpdateView.as_view(), name="categoria_editar"),
    path("gestao/equipes/", views.EquipeAtendimentoListView.as_view(), name="equipes"),
    path("gestao/equipes/novo/", views.EquipeAtendimentoCreateView.as_view(), name="equipe_nova"),
    path("gestao/equipes/<int:pk>/editar/", views.EquipeAtendimentoUpdateView.as_view(), name="equipe_editar"),
    path("gestao/sla/", views.RegraSLAListView.as_view(), name="sla_regras"),
    path("gestao/sla/novo/", views.RegraSLACreateView.as_view(), name="sla_nova"),
    path("gestao/sla/<int:pk>/editar/", views.RegraSLAUpdateView.as_view(), name="sla_editar"),
    path("gestao/topicos/", views.TopicoAjudaListView.as_view(), name="topicos"),
    path("gestao/topicos/novo/", views.TopicoAjudaCreateView.as_view(), name="topico_novo"),
    path("gestao/topicos/<int:pk>/editar/", views.TopicoAjudaUpdateView.as_view(), name="topico_editar"),
    path("gestao/respostas/", views.RespostaProntaListView.as_view(), name="respostas"),
    path("gestao/respostas/nova/", views.RespostaProntaCreateView.as_view(), name="resposta_nova"),
    path("gestao/respostas/<int:pk>/editar/", views.RespostaProntaUpdateView.as_view(), name="resposta_editar"),
    path("gestao/conhecimento/", views.ArtigoConhecimentoListView.as_view(), name="artigos"),
    path("gestao/conhecimento/novo/", views.ArtigoConhecimentoCreateView.as_view(), name="artigo_novo"),
    path("gestao/conhecimento/<int:pk>/editar/", views.ArtigoConhecimentoUpdateView.as_view(), name="artigo_editar"),
    path("gestao/servicos/", views.ServicoCatalogoListView.as_view(), name="servicos"),
    path("gestao/servicos/novo/", views.ServicoCatalogoCreateView.as_view(), name="servico_novo"),
    path("gestao/servicos/<int:pk>/editar/", views.ServicoCatalogoUpdateView.as_view(), name="servico_editar"),
    path("gestao/tecnicos/", views.TecnicoListView.as_view(), name="tecnicos"),
    path("gestao/tecnicos/novo/", views.TecnicoCreateView.as_view(), name="tecnico_novo"),
    path("gestao/relatorios/chamados/", views.RelatorioChamadosView.as_view(), name="relatorio"),
    path("gestao/relatorios/chamados/exportar/xls/", views.exportar_relatorio_xls, name="relatorio_xls"),
    path("gestao/relatorios/chamados/exportar/pdf/", views.exportar_relatorio_pdf, name="relatorio_pdf"),
]
