# Generated by Django 5.2.14 on 2026-06-09 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('endereco', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContratoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
                ('ano', models.PositiveIntegerField(default=2026)),
                ('processo_administrativo', models.CharField(blank=True, max_length=80)),
                ('objeto', models.TextField()),
                ('lei_regencia', models.CharField(choices=[('14133', 'Lei 14.133/2021'), ('8666', 'Lei 8.666/1993'), ('outra', 'Outra base legal')], default='14133', max_length=20)),
                ('modalidade', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(choices=[('continuado', 'Servico continuado'), ('escopo', 'Escopo definido'), ('fornecimento', 'Fornecimento'), ('obra', 'Obra/engenharia'), ('ti', 'Solucao de TIC'), ('outro', 'Outro')], default='continuado', max_length=20)),
                ('valor_global', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_assinatura', models.DateField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('a_vencer', 'A vencer'), ('vencido', 'Vencido'), ('encerrado', 'Encerrado'), ('rescindido', 'Rescindido')], default='vigente', max_length=20)),
                ('permite_prorrogacao', models.BooleanField(default=True)),
                ('limite_prorrogacao_meses', models.PositiveIntegerField(default=120, help_text='Limite operacional cadastrado para controle interno. Confirme a base legal antes de formalizar.')),
                ('alerta_dias', models.PositiveIntegerField(default=90)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiscalizados', to=settings.AUTH_USER_MODEL)),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_geridos', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.fornecedor')),
            ],
            options={
                'verbose_name': 'contrato publico',
                'verbose_name_plural': 'contratos publicos',
                'ordering': ['data_fim', 'numero'],
                'unique_together': {('numero', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='AditivoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('prazo', 'Prazo'), ('valor', 'Valor'), ('quantitativo', 'Quantitativo'), ('reajuste', 'Reajuste'), ('outro', 'Outro')], default='prazo', max_length=20)),
                ('data_assinatura', models.DateField()),
                ('nova_data_fim', models.DateField(blank=True, null=True)),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contratos.contratopublico')),
            ],
            options={
                'verbose_name': 'aditivo contratual',
                'verbose_name_plural': 'aditivos contratuais',
                'ordering': ['-data_assinatura', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProrrogacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_em', models.DateTimeField(auto_now_add=True)),
                ('novo_fim', models.DateField(verbose_name='nova data final pretendida')),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('solicitado', 'Solicitado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('formalizado', 'Formalizado')], default='solicitado', max_length=20)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('observacao_decisao', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prorrogacoes', to='contratos.contratopublico')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisoes_prorrogacao', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_prorrogacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido de prorrogacao',
                'verbose_name_plural': 'pedidos de prorrogacao',
                'ordering': ['-solicitado_em'],
            },
        ),
    ]
