# Generated by Django 5.2.14 on 2026-06-10 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos/anexos/%Y/%m/')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato assinado'), ('edital', 'Edital'), ('termo_referencia', 'Termo de referencia'), ('aditivo', 'Aditivo'), ('parecer', 'Parecer juridico'), ('portaria', 'Portaria fiscal/gestor'), ('fiscalizacao', 'Relatorio de fiscalizacao'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='contratos.contratopublico')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'anexo de contrato',
                'verbose_name_plural': 'anexos de contratos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
