from django.urls import path

from . import views


app_name = "inventario"

urlpatterns = [
    path("agente/coleta/", views.receber_coleta_agente, name="agente_coleta"),
    path(
        "agente/coleta/solicitada/",
        views.consultar_solicitacao_coleta_agente,
        name="agente_coleta_solicitada",
    ),
    path("agente/configuracao/", views.configuracao_agente, name="agente_config"),
    path("agente/downloads/", views.downloads_agente, name="agente_downloads"),
    path("agente/windows/download/", views.baixar_agente_windows, name="agente_windows_download"),
    path("agente/linux/download/", views.baixar_agente_linux, name="agente_linux_download"),
    path("agentes/saude/", views.SaudeAgentesView.as_view(), name="agentes_saude"),
    path("agentes/<int:pk>/solicitar-coleta/", views.solicitar_coleta_agente, name="agente_solicitar_coleta"),
    path("sondas/coleta/", views.receber_coleta_sonda, name="sonda_coleta"),
    path("sondas/", views.SondaRemotaListView.as_view(), name="sondas"),
    path("sondas/nova/", views.SondaRemotaCreateView.as_view(), name="sonda_nova"),
    path("sondas/<int:pk>/", views.SondaRemotaDetailView.as_view(), name="sonda_detalhe"),
    path("sondas/<int:pk>/editar/", views.SondaRemotaUpdateView.as_view(), name="sonda_editar"),
    path("sondas/<int:pk>/token/", views.regenerar_token_sonda, name="sonda_token"),
    path("sondas/<int:pk>/script/", views.baixar_script_sonda, name="sonda_script"),
    path("", views.InventarioPainelView.as_view(), name="painel"),
    path("relatorios/", views.RelatorioInventarioView.as_view(), name="relatorio"),
    path("relatorios/exportar/xls/", views.exportar_relatorio_inventario_xls, name="relatorio_xls"),
    path("relatorios/exportar/pdf/", views.exportar_relatorio_inventario_pdf, name="relatorio_pdf"),
    path("ativos/", views.AtivoRedeListView.as_view(), name="ativos"),
    path("ativos/identificacao/<str:token>/", views.identificacao_publica_ativo, name="ativo_identificacao"),
    path("ativos/sem-comunicacao/", views.AtivosSemComunicacaoView.as_view(), name="ativos_sem_comunicacao"),
    path("ativos/duplicados/", views.AtivosDuplicadosView.as_view(), name="ativos_duplicados"),
    path("ativos/duplicados/mesclar/", views.MesclarAtivosView.as_view(), name="ativos_mesclar"),
    path("ativos/sem-comunicacao/<int:pk>/verificar/", views.verificar_ativo_sem_comunicacao, name="ativo_sem_comunicacao_verificar"),
    path("ativos/sem-comunicacao/<int:pk>/arquivar/", views.arquivar_ativo_sem_comunicacao, name="ativo_sem_comunicacao_arquivar"),
    path("ativos/sem-comunicacao/<int:pk>/reativar/", views.reativar_ativo_arquivado, name="ativo_arquivado_reativar"),
    path("ativos/sem-comunicacao/<int:pk>/excluir/", views.excluir_ativo_arquivado, name="ativo_arquivado_excluir"),
    path("ativos/exportar/xls/", views.exportar_ativos_xls, name="ativos_xls"),
    path("ativos/importar/csv/", views.ImportarAtivosCSVView.as_view(), name="ativos_importar_csv"),
    path("ativos/excluir-lote/", views.excluir_ativos_lote, name="ativos_excluir_lote"),
    path("ativos/verificar-status/", views.verificar_status_ativos_lote, name="ativos_verificar_status"),
    path("ativos/novo/", views.AtivoRedeCreateView.as_view(), name="ativo_novo"),
    path("ativos/<int:pk>/", views.AtivoRedeDetailView.as_view(), name="ativo_detalhe"),
    path("ativos/<int:pk>/editar/", views.AtivoRedeUpdateView.as_view(), name="ativo_editar"),
    path("ativos/<int:pk>/qr.png", views.qr_code_ativo, name="ativo_qr"),
    path("ativos/<int:pk>/etiqueta.pdf", views.etiqueta_ativo_pdf, name="ativo_etiqueta"),
    path("ativos/<int:pk>/arquivar/", views.arquivar_ativo, name="ativo_arquivar"),
    path("ativos/<int:pk>/excluir/", views.excluir_ativo, name="ativo_excluir"),
    path("ativos/<int:pk>/verificar-status/", views.verificar_status_ativo, name="ativo_verificar_status"),
    path("ativos/<int:pk>/revarrer/", views.revarrer_ativo, name="ativo_revarrer"),
    path("ativos/<int:pk>/ocorrencias/nova/", views.registrar_ocorrencia, name="ocorrencia_nova"),
    path("ativos/<int:pk>/relacionamentos/novo/", views.registrar_relacionamento, name="relacionamento_novo"),
    path("ativos/<int:pk>/movimentar/", views.movimentar_ativo, name="ativo_movimentar"),
    path("ativos/<int:pk>/termos/novo/", views.criar_termo_responsabilidade, name="ativo_termo_novo"),
    path("termos/<int:pk>.pdf", views.termo_responsabilidade_pdf, name="termo_pdf"),
    path("tipos/", views.TipoAtivoListView.as_view(), name="tipos"),
    path("tipos/novo/", views.TipoAtivoCreateView.as_view(), name="tipo_novo"),
    path("tipos/<int:pk>/editar/", views.TipoAtivoUpdateView.as_view(), name="tipo_editar"),
    path("snmp/", views.CredencialSNMPListView.as_view(), name="snmp"),
    path("snmp/nova/", views.CredencialSNMPCreateView.as_view(), name="snmp_nova"),
    path("snmp/<int:pk>/editar/", views.CredencialSNMPUpdateView.as_view(), name="snmp_editar"),
    path("faixas/", views.FaixaRedeListView.as_view(), name="faixas"),
    path("faixas/nova/", views.FaixaRedeCreateView.as_view(), name="faixa_nova"),
    path("faixas/<int:pk>/editar/", views.FaixaRedeUpdateView.as_view(), name="faixa_editar"),
    path("faixas/<int:pk>/varrer-snmp/", views.iniciar_varredura_snmp, name="varrer_snmp"),
    path("agendamentos/", views.AgendamentoVarreduraListView.as_view(), name="agendamentos"),
    path("agendamentos/novo/", views.AgendamentoVarreduraCreateView.as_view(), name="agendamento_novo"),
    path("agendamentos/<int:pk>/editar/", views.AgendamentoVarreduraUpdateView.as_view(), name="agendamento_editar"),
]
